-- Advanced Database Features

-- 1. Price History Audit Table
CREATE TABLE PriceHistory (
    history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES Product(product_id),
    old_price NUMBER(10, 2),
    new_price NUMBER(10, 2),
    change_date DATE DEFAULT SYSDATE
);

-- 2. Trigger: Audit Price Changes
CREATE OR REPLACE TRIGGER trg_audit_price_change
AFTER UPDATE OF price ON Product
FOR EACH ROW
BEGIN
    IF :OLD.price != :NEW.price THEN
        INSERT INTO PriceHistory (product_id, old_price, new_price)
        VALUES (:NEW.product_id, :OLD.price, :NEW.price);
    END IF;
END;
/

-- 3. Trigger: Prevent Negative Stock
CREATE OR REPLACE TRIGGER trg_prevent_negative_stock
BEFORE UPDATE OF stock_quantity ON Product
FOR EACH ROW
BEGIN
    IF :NEW.stock_quantity < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Stock quantity cannot be negative.');
    END IF;
END;
/

-- 4. Trigger: Update Seller Total Sales
CREATE OR REPLACE TRIGGER trg_update_seller_sales
AFTER INSERT ON OrderItem
FOR EACH ROW
DECLARE
    v_seller_id NUMBER;
    v_total_sale NUMBER;
BEGIN
    -- Get Seller ID for the product
    SELECT seller_id INTO v_seller_id FROM Product WHERE product_id = :NEW.product_id;
    
    v_total_sale := :NEW.quantity * :NEW.price_at_purchase;
    
    UPDATE Seller SET total_sales = total_sales + v_total_sale WHERE seller_id = v_seller_id;
END;
/

-- 5. Stored Procedure: Checkout with Locking (Serialization)
CREATE OR REPLACE PROCEDURE proc_checkout_order (
    p_customer_id IN NUMBER,
    p_shipping_address_id IN NUMBER,
    p_payment_method IN VARCHAR2,
    p_order_id OUT NUMBER
) AS
    v_total_amount NUMBER := 0;
    v_cart_count NUMBER;
    
    CURSOR c_cart_items IS
        SELECT c.product_id, c.quantity, p.price, p.stock_quantity
        FROM Cart c JOIN Product p ON c.product_id = p.product_id
        WHERE c.customer_id = p_customer_id
        FOR UPDATE OF p.stock_quantity; -- LOCKS the product rows
        
    TYPE t_cart_item IS RECORD (
        product_id NUMBER,
        quantity NUMBER,
        price NUMBER,
        stock_quantity NUMBER
    );
    
    v_item t_cart_item;
BEGIN
    -- Check if cart is empty
    SELECT COUNT(*) INTO v_cart_count FROM Cart WHERE customer_id = p_customer_id;
    IF v_cart_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Cart is empty.');
    END IF;

    -- Calculate Total & Validate Stock (while locking)
    OPEN c_cart_items;
    LOOP
        FETCH c_cart_items INTO v_item;
        EXIT WHEN c_cart_items%NOTFOUND;
        
        IF v_item.quantity > v_item.stock_quantity THEN
            RAISE_APPLICATION_ERROR(-20003, 'Insufficient stock for product ID: ' || v_item.product_id);
        END IF;
        
        v_total_amount := v_total_amount + (v_item.price * v_item.quantity);
    END LOOP;
    CLOSE c_cart_items;
    
    -- Create Order
    INSERT INTO Orders (customer_id, total_amount, shipping_address_id, status)
    VALUES (p_customer_id, v_total_amount, p_shipping_address_id, 'Pending')
    RETURNING order_id INTO p_order_id;
    
    -- Process Items
    OPEN c_cart_items; -- Re-open to process (locks are still held until commit)
    LOOP
        FETCH c_cart_items INTO v_item;
        EXIT WHEN c_cart_items%NOTFOUND;
        
        -- Insert Order Item
        INSERT INTO OrderItem (order_id, product_id, quantity, price_at_purchase)
        VALUES (p_order_id, v_item.product_id, v_item.quantity, v_item.price);
        
        -- Update Stock
        UPDATE Product 
        SET stock_quantity = stock_quantity - v_item.quantity
        WHERE product_id = v_item.product_id;
    END LOOP;
    CLOSE c_cart_items;
    
    -- Create Payment
    INSERT INTO Payment (order_id, amount, payment_method, status)
    VALUES (p_order_id, v_total_amount, p_payment_method, 'Success');
    
    -- Clear Cart
    DELETE FROM Cart WHERE customer_id = p_customer_id;
    
    COMMIT; -- Releases locks
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK; -- Releases locks and undoes changes
        RAISE;
END;
/

-- 6. Add Shipping Columns to Orders Table
ALTER TABLE Orders ADD (
    tracking_number VARCHAR2(100),
    carrier VARCHAR2(50),
    shipped_date DATE
);
